export const metadata = {
  title: "Emergency Rental Assistance | Loan Application",
  description: "Generated by create next app",
};

export default function LoanProcessLayout({ children }) {
  return <main>{children}</main>;
}
